/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.border.Border;

/**
 *
 * @author Marcos
 */
public class JFrmProcessamento extends javax.swing.JFrame {

    private List listaRegistros;
    private SistecController sistecController;
    private AcademicoController academicoController;
    private DefaultListModel lista1, lista2, lista3;

    /**
     * Creates new form JFrmProcessamento
     */
    public JFrmProcessamento() {
        initComponents();
        setTitle("Processamento de arquivos do SISTEC e ACADÊMICO");
        setExtendedState(MAXIMIZED_BOTH);
        jTabbedPane1.setSelectedIndex(0);
        Border borderSistec = BorderFactory.createTitledBorder("Sistec");
        jPanel4.setBorder(borderSistec);
        Border borderAcademico = BorderFactory.createTitledBorder("Academico");
        jPanel5.setBorder(borderAcademico);

        sistecController = new SistecController();
        jTblSistec.setModel(sistecController);

        academicoController = new AcademicoController();
        jTblAcademico.setModel(academicoController);

        lista1 = new DefaultListModel();
        jList1.setModel(lista1);
        lista2 = new DefaultListModel();
        jList2.setModel(lista2);
        lista3 = new DefaultListModel();
        jList3.setModel(lista3);
    }

    public String diretorioAtual() {
        Path currentRelativePath = Paths.get("");
        return currentRelativePath.toAbsolutePath().toString();
    }

    public void lerArquivoSistec(String arquivo) {
        BufferedReader br = null;
        listaRegistros = new ArrayList();
        try {
            br = new BufferedReader(new FileReader(arquivo));
            String linha;
            linha = br.readLine();
            sistecController.setCabecalho(linha);
            while ((linha = br.readLine()) != null) {
                listaRegistros.add(linha);
            }
            sistecController.setDados(listaRegistros);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

        }
    }

    public void processarArquivoSistec() {
        sistecController.setSeparador((String) jCboSeparadorSistec.getSelectedItem());
        lerArquivoSistec(jTxtArquivoSistec.getText());
        lista1.clear();
        jCboStatusSistec.removeAllItems();
        for (int i = 0; i < sistecController.getCabecalho().length; i++) {
            lista1.add(i, sistecController.getCabecalho()[i]);
            jCboStatusSistec.addItem(sistecController.getCabecalho()[i]);
        }
        jList1.setSelectedIndex(0);
    }

    public void lerArquivoAcademico(String arquivo) {
        BufferedReader br = null;
        listaRegistros = new ArrayList();
        try {
            br = new BufferedReader(new FileReader(arquivo));
            String linha;
            linha = br.readLine();
            academicoController.setCabecalho(linha);
            while ((linha = br.readLine()) != null) {
                listaRegistros.add(linha);
            }
            academicoController.setDados(listaRegistros);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
        }
    }

    public void processarArquivoAcademico() {
        academicoController.setSeparador((String) jCboSeparadorAcademico.getSelectedItem());
        lerArquivoAcademico(jTxtArquivoAcademico.getText());
        lista3.clear();
        jCboStatusAcademico.removeAllItems();
        for (int i = 0; i < academicoController.getCabecalho().length; i++) {
            lista3.add(i, academicoController.getCabecalho()[i]);
            jCboStatusAcademico.addItem(academicoController.getCabecalho()[i]);
        }
        jList3.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtArquivoSistec = new javax.swing.JTextField();
        jBtnArquivoSistec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCboSeparadorSistec = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCboStatusSistec = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtArquivoAcademico = new javax.swing.JTextField();
        jBtnArquivoAcademico = new javax.swing.JButton();
        jCboSeparadorAcademico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCboStatusAcademico = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTblSistec = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTblAcademico = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jChbSalvar = new javax.swing.JCheckBox();
        jBtnProcessar = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome do Arquivo");

        jBtnArquivoSistec.setText("...");
        jBtnArquivoSistec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnArquivoSistecActionPerformed(evt);
            }
        });

        jLabel3.setText("Separador");

        jCboSeparadorSistec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", ";", "," }));
        jCboSeparadorSistec.setSelectedIndex(1);

        jLabel6.setText("Campo de Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTxtArquivoSistec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnArquivoSistec))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboSeparadorSistec, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboStatusSistec, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtArquivoSistec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnArquivoSistec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCboSeparadorSistec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCboStatusSistec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome do Arquivo");

        jBtnArquivoAcademico.setText("...");
        jBtnArquivoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnArquivoAcademicoActionPerformed(evt);
            }
        });

        jCboSeparadorAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", ";", "," }));
        jCboSeparadorAcademico.setSelectedIndex(2);

        jLabel4.setText("Separador");

        jLabel7.setText("Campo de Status");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 478, Short.MAX_VALUE))
                    .addComponent(jTxtArquivoAcademico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnArquivoAcademico))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboSeparadorAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboStatusAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtArquivoAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnArquivoAcademico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCboSeparadorAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jCboStatusAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jList1);

        jScrollPane4.setViewportView(jList2);

        jScrollPane5.setViewportView(jList3);

        jLabel5.setText("Campos a serem comparados");

        jBtnAdicionar.setText("Adicionar");
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnRemover.setText("Remover");
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBtnAdicionar)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnRemover)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnAdicionar)
                            .addComponent(jBtnRemover))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5)))
        );

        jTabbedPane1.addTab("Arquivos CSV", jPanel1);

        jTblSistec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTblSistec);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sistec", jPanel2);

        jTblAcademico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTblAcademico);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Acadêmico", jPanel6);

        jToolBar1.setRollover(true);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jChbSalvar.setText("Salvar Informações");
        jPanel3.add(jChbSalvar);

        jBtnProcessar.setText("Processar");
        jBtnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcessarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnProcessar);

        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnLimpar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnArquivoSistecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnArquivoSistecActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc;
        //verifica se tem alguma informacao no JTextField
        if (jTxtArquivoSistec.getText().trim().isEmpty()) {
            fc = new JFileChooser();
        } else {
            fc = new JFileChooser(jTxtArquivoSistec.getText());
        }
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //pega o arquivo selecionado 
            File file = fc.getSelectedFile();
            //seta a informação do arquivo selecionado
            jTxtArquivoSistec.setText(file.getPath());
            //
            processarArquivoSistec();
            jTblSistec.setModel(sistecController);
        }
    }//GEN-LAST:event_jBtnArquivoSistecActionPerformed

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        //jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex() + 1);
        jTxtArquivoAcademico.setText("");
        jTxtArquivoSistec.setText("");
        jCboStatusSistec.setSelectedIndex(-1);
        jCboStatusAcademico.setSelectedIndex(-1);
        sistecController.setDados(null);
        academicoController.setDados(null);
        lista1.removeAllElements();
        lista2.removeAllElements();
        lista3.removeAllElements();

    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jBtnArquivoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnArquivoAcademicoActionPerformed
        // TODO add your handling code here:        
        final JFileChooser fc;
        if (jTxtArquivoAcademico.getText().trim().isEmpty()) {
            fc = new JFileChooser();
        } else {
            fc = new JFileChooser(jTxtArquivoAcademico.getText());
        }
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTxtArquivoAcademico.setText(file.getPath());
            //
            processarArquivoAcademico();
        }

    }//GEN-LAST:event_jBtnArquivoAcademicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String dirArq = diretorioAtual() + "\\dados.cfg";
        File arquivo = new File(dirArq);
        if (arquivo.exists()) {
            BufferedReader br = null;
            try {
                br = new BufferedReader(new FileReader(dirArq));
                String linha = br.readLine();
                jTxtArquivoSistec.setText(linha);
                linha = br.readLine();
                if (linha != null) {
                    jCboSeparadorSistec.setSelectedIndex(Integer.parseInt(linha));
                    processarArquivoSistec();
                }
                linha = br.readLine();
                if (linha != null) {
                    jCboStatusSistec.setSelectedIndex(Integer.parseInt(linha));
                }
                //lendo e processamento ACADEMICO
                linha = br.readLine();
                if (linha != null) {
                    jTxtArquivoAcademico.setText(linha);
                }
                linha = br.readLine();
                if (linha != null) {
                    jCboSeparadorAcademico.setSelectedIndex(Integer.parseInt(linha));
                    processarArquivoAcademico();
                }
                linha = br.readLine();
                if (linha != null) {
                    jCboStatusAcademico.setSelectedIndex(Integer.parseInt(linha));
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(JDlgArquivos.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
            }
        } else {
            System.out.println("Arquivo não existe.");
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:        
        if (jChbSalvar.isSelected()) {
            String arquivo = diretorioAtual() + "\\dados.cfg";
            System.out.println(arquivo);
            try {
                PrintWriter pw;
                //pw = new PrintWriter(new BufferedWriter(new FileWriter(arquivo, true)));
                //cria arquivo e sobrepoe se existir
                pw = new PrintWriter(new BufferedWriter(new FileWriter(arquivo)));
                //SISTEC
                if (jTxtArquivoSistec.getText().trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jTxtArquivoSistec.getText());
                }

                if (jCboSeparadorSistec.getSelectedIndex() == -1 & ((String) jCboSeparadorSistec.getSelectedItem()).trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jCboSeparadorSistec.getSelectedIndex());
                }

                if (jCboStatusSistec.getSelectedIndex() == -1 & ((String) jCboStatusSistec.getSelectedItem()).trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jCboStatusSistec.getSelectedIndex());
                }
                //ACADEMICO
                if (jTxtArquivoAcademico.getText().trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jTxtArquivoAcademico.getText());
                }
                if (jCboSeparadorAcademico.getSelectedIndex() == -1 & ((String) jCboSeparadorAcademico.getSelectedItem()).trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jCboSeparadorAcademico.getSelectedIndex());
                }
                if (jCboStatusAcademico.getSelectedIndex() == -1 & ((String) jCboStatusAcademico.getSelectedItem()).trim().isEmpty()) {
                    pw.println("");
                } else {
                    pw.println(jCboStatusAcademico.getSelectedIndex());
                }
                pw.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrmProcessamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        // TODO add your handling code here:
        lista2.addElement(lista1.get(jList1.getSelectedIndex()) + "=>" + lista3.get(jList3.getSelectedIndex()));
        lista1.remove(jList1.getSelectedIndex());
        lista3.remove(jList3.getSelectedIndex());
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed
        // TODO add your handling code here:
        lista2.remove(jList2.getSelectedIndex());
    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 1) {
            //JOptionPane.showMessageDialog(null, "sistec");
        }
        if (jTabbedPane1.getSelectedIndex() == 2) {
            //JOptionPane.showMessageDialog(null, "academico");
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jBtnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcessarActionPerformed
        // TODO add your handling code here:
        List dadosSistec = sistecController.getDados();
        List dadosAcademico = academicoController.getDados();
        //pegar o campo do list e guardar o indice do sistec e academico
        String[] camposBusca = ((String) lista2.get(0)).split("=>");
        //procura indice do campo que será buscado nos dados do SISTEC
        int indSistec = 0;
        for (int i = 0; i < jCboStatusSistec.getItemCount(); i++) {
            if (jCboStatusSistec.getItemAt(i).equals(camposBusca[0])) {
                indSistec = i;
                break;
            }
        }
        //procura indice do campo que será buscado nos dados do ACADEMICO
        int indAcademico = 0;
        for (int i = 0; i < jCboStatusAcademico.getItemCount(); i++) {
            if (jCboStatusAcademico.getItemAt(i).equals(camposBusca[1])) {
                indAcademico = i;
                break;
            }
        }
        String linha1, linha2, valorSistec, valorAcademico;
        String[] camposSistec, camposAcademico;
        for (int i = 0; i < dadosSistec.size(); i++) {
            linha1 = (String) dadosSistec.get(i);
            camposSistec = linha1.split((String) jCboSeparadorSistec.getSelectedItem());
            valorSistec = camposSistec[indSistec];
            //System.out.println(valorSistec);
            //procura campo do sistec no academico
            boolean achou = false;
            for (int j = 0; j < dadosAcademico.size(); j++) {
                linha2 = (String) dadosAcademico.get(j);
                camposAcademico = linha2.split((String) jCboSeparadorAcademico.getSelectedItem());
                if (valorSistec.equals(camposAcademico[indAcademico])) {
                    achou = true;
                }
            }
            if (achou) {
                System.out.println("achou =" + valorSistec);//+ " - " + camposAcademico[indAcademico]);
            } else {
                System.out.println("NAO achou =" + valorSistec);// + " - " + camposAcademico[indAcademico]);
            }
        }
        //System.out.println("indice"+indSistec);
        //usar esse indice para acessar o valor no List dados no academico
        //procurar o dado do sistec no academico
        //se nao existir guardar a linha
    }//GEN-LAST:event_jBtnProcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmProcessamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmProcessamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmProcessamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmProcessamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmProcessamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnArquivoAcademico;
    private javax.swing.JButton jBtnArquivoSistec;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnProcessar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JComboBox<String> jCboSeparadorAcademico;
    private javax.swing.JComboBox<String> jCboSeparadorSistec;
    private javax.swing.JComboBox<String> jCboStatusAcademico;
    private javax.swing.JComboBox<String> jCboStatusSistec;
    private javax.swing.JCheckBox jChbSalvar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblAcademico;
    private javax.swing.JTable jTblSistec;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtArquivoAcademico;
    private javax.swing.JTextField jTxtArquivoSistec;
    // End of variables declaration//GEN-END:variables
}
